### ISSUE TITLE
Blink fails to compile with V 1.0.2 of the core libraries

### ISSUE THREAD

**Issue by taichichuan** [energia/cc3200-core#18]
I tried to compile the blink example after updating the CC3200 library to 1.0.2 and it fails with:

In file included from c:\users\mike\appdata\local\energia15\packages\energia\tools\arm-none-eabi-gcc\6.3.1-20170620\arm-none-eabi\include\string.h:10:0,

                 from C:\Users\mike\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\cores\cc3200/Energia.h:8,

                 from C:\Users\mike\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\cores\cc3200/Arduino.h:3,

                 from sketch\Blink.ino.cpp:1:

c:\users\mike\appdata\local\energia15\packages\energia\tools\arm-none-eabi-gcc\6.3.1-20170620\arm-none-eabi\include\stdlib.h:225:8: error: conflicting declaration of C function 'char* utoa(unsigned int, char*, int)'

 char * _EXFUN(utoa,(unsigned, char *, int));

        ^

In file included from C:\Users\mike\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\cores\cc3200/Energia.h:10:0,

                 from C:\Users\mike\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\cores\cc3200/Arduino.h:3,

                 from sketch\Blink.ino.cpp:1:

C:\Users\mike\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\cores\cc3200/itoa.h:34:14: note: previous declaration 'char* utoa(long unsigned int, char*, int)'

 extern char* utoa( unsigned long value, char *string, int radix ) ;

              ^~~~

exit status 1
Error compiling for board CC3200-LAUNCHXL (80MHz).

**Comment by taichichuan** [comment]
OK, this appears to be an issue with the GNU 6.3 compiler that was installed with one of the Energia updates.  If I move the 6.3 compiler out of the tools directory, everything compiles again.  So, what's up with the 6.3 compiler?

**Comment by rei-vilo** [comment]
See #19.

**Comment by robertinant** [comment]
fixed with fbc3f83376f7c8fff1a842db030d263c3e4f236d
